### ISSUE TITLE
grids

### ISSUE THREAD

**Issue by guer0125** [guer0125/components-on-a-grid#1]
Hi Hannah, thanks a lot for your help

i believe i have everything i need, but i'm still having trouble matching the image enough to submit. what can i do to fix it? also, i keep getting the error for the font

i never know if it wants quotes or not and it keep saying it's expecting something else but i'm writing exactly what markbot is asking.

thank you again

@HannahDelaney

**Comment by HannahDelaney** [comment]
Hey!

So for the font, the base font isn't Patua One. It's applied in certain places, but you'll notice in the screenshots that the body copy font is different. If you look at the assignment brief on Learn the Web, there's a font you're missing in your css.

The Line 41 error is that you've added a rem unit to a value of 0. When something is at 0, it doesn't need a unit. So it should read `margin: 0` vs. `margin: 0rem`, as an example. Although I also don't think you need that margin line at all, for this assignment.

As for the screenshot matching, you'll probably just need to play with your margin/paddings a bit, and how you've arranged your grid, grid-areas and figures. Little hint is that you'll need a `padding: 1rem` on your body tag. Also, if you change your main to be `display: contents` instead of `display:grid` (and remove the other selectors that are not the display) I think that will help get you closer. There is an explanation and reference to the `display: contents` thing here: https://learn-the-web.algonquindesign.ca/topics/css-grids/#display-contents

Good luck!

**Comment by guer0125** [comment]
Than you Hannah, so i tried Open sans in html and it's still saying it's expecting something else lol

**Comment by HannahDelaney** [comment]
Yeah, Open Sans won't work either. Look under details here: https://learn-the-web.algonquindesign.ca/courses/web-design-2/week-02/#components-on-a-grid

**Comment by guer0125** [comment]
i saw it's Georgia under .markbot.yml in atom, but markbot is still saying it's wrong, so i don't know what i'm doing wrong,  i tried
font-family: Georgia;
font-family: "Georgia";
font-family: "Georgia", serif;
font-family: "Georgia;, serif";

**Comment by guer0125** [comment]
also, i'm not sure how to put the padding or margin in between the bottom pictures. thanks for replying on a sunday night btw

**Comment by HannahDelaney** [comment]
If it's a single word font name like Georgia, you don't need the quotes. Only if it's more than one word. The serif/sans bit gives specifications if the font you specify doesn't load for some reason, it will default to some other serif font.
It should be:
`font-family: Georgia, serif;`

You should be able to target the space between the figures at the bottom by using the "gap" css grid selector. :)

**Comment by guer0125** [comment]
thank you :)
